<div class="col-md-6">
    <div>
        <h3>Hello <?= $this->session->get('login'); ?>!</h3>
    </div>
    <?php  $this->flashSession->output();?>
    <form action="/agent/account" method="POST">
        <div  class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input name="email"  type="email" class="form-control" id="exampleInputEmail1" value="<?= $agent->email ?>">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Login</label>
            <input name="login" type="text" class="form-control" id="exampleInputPassword1" value="<?= $agent->login ?>">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Confirm password</label>
            <input name="confirmPas" type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirm password">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>
<div class="col-md-4 col-md-offset-2">
    <a class="btn btn-primary col-md-offset-7" href="/aut/logout"> Log out
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>
<script>
    document.getElementById('account').classList.add('active');
</script>