<div class="col-md-3"></div>
<div class="border-form  col-md-6">
    <label class="col-sm-2"><h2><b>Registration</b></h2></label><br><br><br><br>
	<form class="form-horizontal" method="POST" action="/registration/register">

        <div class="form-group">
            <label for="inputEmail3" class="col-sm-5 control-label">Login</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="login" id="inputEmail3" placeholder="Login">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label">Password</label>
            <div class="col-sm-5">
                <input type="password" class="form-control" name="password" id="inputPassword3" placeholder="Password">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label">Email</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="email" id="inputPassword3" placeholder="Email">
            </div>
        </div>
        <div class="form-group">
            <div class="center-block">
                <a href="/" style="margin:5px;" class="btn btn-default">Back</a>
                <button type="submit"  style="margin:5px;" class="btn btn-success">Sign up</button>
            </div>
        </div>
    </form>
    <?php  $this->flashSession->output() ?>
</div>
<div class="col-md-3"></div>

