
<div class="col-md-4"></div>
<div class="border-form col-md-4">
    <label class="col-sm-2"><h2><b>Authorization</b></h2></label><br><br><br><br>
    <form class="form-horizontal" method="POST" action="/aut/aut">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-5 control-label">Login</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="login" id="inputEmail3" placeholder="Login">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label">Password</label>
            <div class="col-sm-5">
                <input type="password" class="form-control" name="password" id="inputPassword3" placeholder="Password">
            </div>
        </div>
        <div class="form-group">
            <div class="center-block">
                <button style="margin:5px;" type="submit" class="btn btn-primary">Sign in</button>
                <a href="/registration" style="margin:5px;" type="submit" class="btn btn-success">Sign up</a>
            </div>
        </div>
    </form>
    <?php  $this->flashSession->output(); ?>
</div>
<div class="col-md-4"></div>
