<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>

 <p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name") ?>
 </p>

 <p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email") ?>
 </p>

 <p>
    <?php echo $this->tag->submitButton("Register") ?>
 </p>

<div class="col-md-4"></div>
<div class="border-form col-md-4">
    <label class="col-sm-2"><h2><b>Authorization</b></h2></label><br><br><br><br>
    <form class="form-horizontal" method="POST" action="/authentication/authenticate">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-5 control-label">Login</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="login" id="inputEmail3" placeholder="Login">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-5 control-label">Password</label>
            <div class="col-sm-5">
                <input type="password" class="form-control" name="password" id="inputPassword3" placeholder="Password">
            </div>
        </div>
        <div class="form-group">
            <div class="center-block">
                <button style="margin:5px;" type="submit" class="btn btn-primary">Sign in</button>
                <a href="/registration" style="margin:5px;" type="submit" class="btn btn-success">Sign up</a>
            </div>
        </div>
    </form>
</div>
<div class="col-md-4"></div>

</form>