<?php $this->partial('shared/search'); ?>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Order id</th>
        <th>User email</th>
        <th>Keys id</th>
        <th>Sum</th>
    </tr>
    </thead>
    <?php
    foreach($orders as $order): ?>
        <tbody>
        <tr>
            <td><?=$order->orderId?></td>
            <td><?=$order->emailUser?></td>
            <td>
                <?php $keys=$order->getKeys(); ?>
                <table id="accordion">
                    <?php if(count($keys) < 5){
                    foreach($keys as $key):?>
                        <tr><td><label><?=$key->keyId?></label></td></tr>
                    <?php endforeach; ?>
                </table>
                <?php }else{ ?>
                    <tr><td><label><?=$keys[0]->keyId?></label></td></tr>
                    <tr data-toggle="collapse" data-target="#collapseTarget"><td><label>...</label></td></tr><?php
                ?><tbody id="collapseTarget" class="collapse"><?php
                $this->partial('shared/collapse');
                ?></tbody><?php
                ?></table><?php
                }
                ?>
            </td>
            <td><?=$order->sum?></td>
        </tr>
        </tbody>
    <?php endforeach ?>
</table>
    <?php $this->partial('shared/paginator'); ?>
<script>
    document.getElementById("orders").classList.add("active");
</script>