<div class="col-md-2"></div>
<div class="col-md-8">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Order id</th>

            <th>User email</th>

            <th>Num of keys</th>

            <th>Keys id</th>

            <th>Sum</th>
        </tr>
        </thead>
        <?php
        foreach($orders as $order): ?>
            <tbody>
            <tr class="success">
                <td><?=$order->orderId?></td>

                <td><?=$order->emailUser?></td>

                <td><?=$order->keyNum?></td>

                <td>
                    <table>

                        <?php foreach($order->getKeys() as $key):?>
                            <tr><td><label><?=$key->keyId?></label></td></tr>
                        <?php endforeach; ?>

                    </table>
                </td>

                <td><?=$order->sum?></td>
            </tr>
            </tbody>
        <?php endforeach ?>
    </table>
</div>
<div class="col-md-2"></div>
<script>
    document.getElementById("main").classList.add("active");
</script>