<div class="col-md-5 col-md-offset-7">
<form method="post" action="/order">
    <div class="input-group">
        <input type="text" name="email" class="form-control" placeholder="Email">
        <span class="input-group-btn">
                <button class="btn btn-default" type="button">
                    Search <span class="glyphicon glyphicon-search"></span>
                </button>
        </span>
    </div>
</form>
</div>