<form class="form-horizontal" method="POST" action="/refund/enter">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-offset-0 col-sm-5 col-md-5">
                    <input type="email" class="form-control" placeholder="Email" name="email"/>
                </div>
                <div class="col-md-offset-4 col-sm-offset-4 col-sm-2 col-md-2">
                    <button type="submit" name="enter" class="btn btn-primary">Enter <span class=""></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>

<?php
//var_dump($_SESSION);
$this->flashSession->output();