<div class="col-md-8"><?php  $this->flashSession->output();?></div>
<form  method = "POST" action = "/refund/indexSend">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>User email</th>
            <th>Num of keys</th>
            <th>Keys id</th>
            <th>Percent</th>
            <th>Final percent</th>
            <th>Date</th>
            <th></th>
        </tr>
        </thead>
        <?php
        foreach($refunds as $refund): ?>
            <tbody>
            <tr class="success">
                <td><?=$refund->email?></td>
                <td><?=$refund->keyNum?></td>
                <td>
                    <?php $i = 0;
                    foreach($refund->keys as $key):
                        $i++;?>
                        <input type="checkbox" name="keyToCancel[<?= $refund->id ?>][<?= $i ?>]" value="<?=$key->keyId?>" />  <?=$key->keyId?><br>
                    <?php endforeach; ?>
                </td>
                <td><?=$refund->percent?></td>
                <td><input name="finalPercent<?=$refund->id?>" type="text" class="form-control" placeholder="<?=$refund->percent?>" value="<?=$refund->percent?>" /></td>
                <td><?=$refund->data?></td>
                <td><button class="form-control" type="submit" name="id_refund" value="<?= $refund->id ?>">Send</button></td>
            </tr>
            </tbody>
        <?php endforeach ?>
    </table>
</form>
<script>
    document.getElementById("main").classList.add("active");
</script>

