<div class="col-md-2"></div>
<div class="col-md-8">
    <form action = "" method = "POST">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>User email</th>
                <th>Num of keys</th>
                <th>Keys id</th>
                <th>Percent</th>
                <th>Final percent</th>
                <th>Date</th>
                <th></th>
            </tr>
            </thead>
            <?php
            var_dump($cancelRequestList);
            var_dump($keysList);
            foreach($cancelRequestList as $refund): ?>
                <tbody>
                <tr class="success">
                    <td><?=$refund->email?></td>
                    <td><?=$refund->keyNum?></td>
                    <td>
                        <?php $i = 0;
                        foreach($keysList as $key->$value):
                            $i++;?>
                            <input type="checkbox" name="keyToCancel[<?= $refund->id ?>][<?= $i ?>]" value="<?=$key['key_id']?>" />  <?=$key['key_id']?><br>
                        <?php endforeach ?>
                    </td>
                    <td><?=$refund['percent']?></td>
                    <td><input   type="text" name="finalPercent" value="<?=$refund['final_percent']?>"></td>
                    <td><?=$refund['data']?></td>
                    <td><button type="submit" name="id_refund" value="<?= $refund['id'] ?>">Send</button></td>
                </tr>
                </tbody>
            <?php endforeach ?>
        </table>
    </form>
</div>
<div class="col-md-2"></div>
<script>
    document.getElementById("main").classList.add("active");
</script>

