<?php  $this->flashSession->output();?>
<form  method = "POST" action = "/refund/indexSend">
    <div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th class="col-md-3">User email</th>
            <th class="col-md-1">Num of keys</th>
            <th class="col-md-3">Keys id</th>
            <th class="col-md-1">Percent</th>
            <th class="col-md-2">Final percent</th>
            <th class="col-md-2">Date</th>
            <th></th>
        </tr>
        </thead>
        <?php
        foreach($refunds as $refund): ?>
            <tbody>
            <tr >
                <td><?=$refund->email?></td>
                <td><?=$refund->keyNum?></td>
                <td>
                    <?php $i = 0;
                    foreach($refund->keys as $key):
                        $i++;?>
                        <input type="checkbox" name="keyToCancel[<?= $refund->id ?>][<?= $i ?>]" value="<?=$key->keyId?>" />  <?=$key->keyId . ' ' . $key->percent . '%'?><br>
                    <?php endforeach; ?>
                </td>
                <td><?=$refund->percent?></td>
                <td><input name="finalPercent<?=$refund->id?>" type="text" class="form-control" placeholder="<?=$refund->percent?>" value="<?=$refund->percent?>" /></td>
                <td><?=$refund->data?></td>
                <td><button class="form-control btn-primary" type="submit" name="id_refund" value="<?= $refund->id ?>">Send </button></td>
            </tr>
            </tbody>
        <?php endforeach ?>
    </table>
    </div>
</form>
<div class="navButtons">
    <?php $this->partial('shared/paginator'); ?>
</div>
<script>
    document.getElementById("main").classList.add("active");
</script>

