<table class="table table-hover">
    <thead>
    <tr>
        <th>Refund id</th>
        <th>User email</th>
        <th>Num of keys</th>
        <th>Keys id</th>
        <th>Percent</th>
        <th>Date</th>
    </tr>
    </thead>
    <?php
    foreach($refunds as $refund):
        ?>
        <tbody>

        <tr
        <?php if ($refund->status == 2) { ?> class="success"
        <?php }  else  if ($refund->status == 3) {?> class="danger"
        <?php }
        else {}?> >

            <?php if ($refund->status == 3 || $refund->status == 2) { ?>
                <td><?=$refund->id?></td>
                <td><?=$refund->email?></td>
                <td><?=$refund->keyNum?></td>
                <td>
                    <table>
                        <?php foreach($refund->getKeys() as $key):?>
                            <tr><td><label><?=$key->keyId?></label></td></tr>
                        <?php endforeach; ?>
                    </table>
                </td>
                <td><?=$refund->percent?></td>
                <td><?=$refund->data?></td>
            </tr>
            </tbody>
    <?php } endforeach; ?>
</table>
<div class="navButtons">
    <?php $this->partial('shared/paginator'); ?>
</div>
<script>
    document.getElementById("report").classList.add("active");
</script>