
<form method="post">
    <div class="row">
        <div><h3>Refund for user <spun style="color: #428bca;"> <?= $email ?></spun></h3></div>
    </div>
<!---add end key_id--->
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-offset-0 col-md-3 col-sm-3">
                    <input type="text" class="form-control" placeholder="key_id" name="key_id"/>
                </div>
                <div class="col-md-offset-5 col-md-2 col-sm-offset-5 col-sm-2">
                    <button type="submit" name="add" class="btn btn-primary">
                        Add <span class=""></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
<form method="post" action = "/refund/send">

<?php
//var_dump($keys);
if (!empty($keys)) {
?>
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th class="col-md-3 col-sm-3">Key id</th>
                        <th>Deactivate?</th>
                    </tr>
                    </thead>
                </table>
                <?php foreach($keys as $key=>$value) : ?>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 checkbox">
                            <label class="col-md-3 col-sm-2" for="<?= $key ?>"><?= $key ?></label>
                            <input class="col-md-10 col-sm-11" id="<?= $key ?>" value="<?= $key ?>" name="cancelKeys[]"  type="checkbox"/>
                        </div>
                        <div class="col-md-offset-2 col-md-2 col-sm-offset-2 col-sm-2">
                            <button type="submit" class="btn btn-primary" name="delete" value="<?= $key ?>" formaction="/refund/del">
                                Del <span class=""></span>
                            </button>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

    <!--sent and percent---->
    <div class="row">
        <div class="col-md-offset-0 col-md-3 col-sm-3">
            <input type="text" class="form-control" placeholder="percent" name="percent"/>
        </div>
        <div class="col-md-offset-1 col-md-3 col-sm-offset-1 col-sm-3">
            <button type="submit" name="send" class="btn btn-primary">
                Send <span class=""></span>
            </button>
        </div>
    </div>

<?php
}
$this->flashSession->output();
?>
</form>
