
<form method="post" action="/refund/set">
    <div class="row">
        <div><h3>Refund for user <spun style="color: #428bca;"> <?= $email ?></spun></h3></div>
    </div>
<!---add end key_id--->
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-offset-0 col-md-3 col-sm-3">
                    <input type="text" class="form-control" placeholder="key_id" name="key_id"/>
                </div>
                <div class="col-md-offset-5 col-md-2 col-sm-offset-5 col-sm-2">
                    <button type="submit" name="add" class="btn btn-primary">
                        Add <span class=""></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
<form method="post" action = "/refund/send">

<?php
if (!empty($keys)) {
?>
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Key id</th>
                        <th>Deactivate?</th>
						<th>Percent</th>
						<th></th>
                    </tr>
                    </thead>
					<tbody>
                <?php foreach($keys as $key) : ?>
					<tr>
						<td><label  for="<?= $key->keyId ?>"><?= $key->keyId ?></label></td>
						<td><input  id="<?= $key->status ?>" value="<?= $key->keyId ?>" name="cancelKeys[]"  type="checkbox"/></td>
						<td><label><?= $key->percent ?></label></td>
						<td>
							<button type="submit" class="btn btn-primary" name="delete" value="<?= $key->keyId ?>" formaction="/refund/del">
								Del <span class=""></span>
							</button>
						</td>
					</tr>
				
                <?php endforeach; ?>
					<tbody>
				</table>
            </div>
        </div>

    <!--sent and percent---->
    <div class="row">
        <div class="col-md-offset-0 col-md-3 col-sm-3">
            <input type="text" class="form-control" placeholder="percent" name="percent"/>
        </div>
        <div class="col-md-offset-1 col-md-3 col-sm-offset-1 col-sm-3">
            <button type="submit" name="send" class="btn btn-primary">
                Send <span class=""></span>
            </button>
        </div>
    </div>

<?php
}
$this->flashSession->output();
?>
</form>
<script>
    document.getElementById("refund").classList.add("active");
</script>