<?php
$this->assets->outputCss();
$this->assets->outputJs();
?>

<!DOCTYPE html>
<html>
<head>
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <nav class= "navbar navbar-default" >
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="col-md-2 navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"><strong>superCRM</strong></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="col-md-6 collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li id="main"><a href="/refund/">main <span class="sr-only">(current)</span></a></li>
                            <li id="refund"><a href="/refund/enter">refund <span class="sr-only">(current)</span></a></li>
                            <li id="orders"><a href="/order">orders <span class="sr-only">(current)</span></a></li>
                            <li id="report"><a href="/refund/received">failed <span class="sr-only">(current)</span></a></li>
                            <li id="account"><a href="/agent/">account <span class="sr-only">(current)</span></a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="col-md-2"></div>
        <div class="col-md-8">
            <?php echo $this->getContent() ?>
        </div>
    <div class="col-md-2"></div>
</div>
<?php $this->assets->outputJs();?>
</body>
</html>